### PR TITLE
Avatar badge

### PR DESCRIPTION
**Pull request by ArjunGTX**
Created Avatar and Badge components. 

ezgif-2-19eab3f44c

### CODE REVIEW

**Review by omgaikwad — COMMENTED** [review]
I looked around all the files including avatar.css and badge.css, the code looks fine, I think you are good to go!

**Comment by anshikaa12** [comment]
Code looks good to go
Just a suggestion from my side is that try to write more info about the avatars and how to use them maybe!
Rest it looks fine!

**Comment by ArjunGTX** [comment]
Yes I will give more information about avatar component. Thankyou for
pointing that out.

**Review by anshikaa12 — APPROVED** [review]
everythings looks good to merge!

**Pull request merged**
