### PR TITLE
Home page

### PR DESCRIPTION
**Pull request by ArjunGTX**
Added Home page. 
Screenshot (32)

### CODE REVIEW

**Comment by KanekarSnehal** [comment]
looks good! you can merge it.

**Comment by spraveenofficial** [comment]
Look cool. You are having some unique classname though :)

**Review by abhijeetekad — APPROVED** [review]

**Comment by AmishMishra11** [comment]
looks good go ahead and merge it

**Comment by ArjunGTX** [comment]
Ok thanks

**Pull request merged**
